In [23]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
import numpy as np
import csv
import os

# training
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.callbacks import TensorBoard

In [24]:
DATA_PATH = os.path.join('mp_data')  # Path for exported data, numpy arrays


#getting dataset values from csv
with open('newlabelstrain.csv', newline='') as f:
    reader = csv.reader(f)
    data = [row[0] for row in reader]


actions = np.array(data)
no_sequences = 30  # thirty videos worth of data
sequence_length = 30  # each video is 30 frame in length

label_map = {label:num for num, label in enumerate(actions)}
print(label_map)

{'on': 0, 'off': 1}


In [25]:
sequences, labels = [], []  # x data, y data
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

x = np.array(sequences)
print(x.shape)
y = to_categorical(labels).astype(int)
print(y)

(60, 30, 63)
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


In [26]:
# creating training partitions

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(57, 30, 63) (3, 30, 63) (57, 2) (3, 2)


In [27]:
# training

log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

model = Sequential() # instantiating the model
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30, 63)))
model.add(LSTM(128, return_sequences=True, activation='relu'))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(actions.shape[0], activation='softmax'))

model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [28]:
model.fit(x_train, y_train, epochs=200, callbacks=[tb_callback])
print(model.summary())

Epoch 1/200
2/2 [==============================] - 3s 523ms/step - loss: 0.6939 - categorical_accuracy: 0.5088
Epoch 2/200
2/2 [==============================] - 0s 56ms/step - loss: 0.6912 - categorical_accuracy: 0.5088
Epoch 3/200
2/2 [==============================] - 0s 37ms/step - loss: 0.6912 - categorical_accuracy: 0.5088
Epoch 4/200
2/2 [==============================] - 0s 39ms/step - loss: 0.6867 - categorical_accuracy: 0.5088
Epoch 5/200
2/2 [==============================] - 0s 47ms/step - loss: 0.6824 - categorical_accuracy: 0.5439
Epoch 6/200
2/2 [==============================] - 0s 39ms/step - loss: 0.6729 - categorical_accuracy: 0.6491
Epoch 7/200
2/2 [==============================] - 0s 39ms/step - loss: 0.6544 - categorical_accuracy: 0.7544
Epoch 8/200
2/2 [==============================] - 0s 36ms/step - loss: 0.6047 - categorical_accuracy: 0.8772
Epoch 9/200
2/2 [==============================] - 0s 34ms/step - loss: 0.5900 - categorical_accuracy: 0.8421
Epoch 10/

2/2 [==============================] - 0s 38ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 74/200
2/2 [==============================] - 0s 36ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 75/200
2/2 [==============================] - 0s 36ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 76/200
2/2 [==============================] - 0s 33ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 77/200
2/2 [==============================] - 0s 31ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 78/200
2/2 [==============================] - 0s 34ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 79/200
2/2 [==============================] - 0s 33ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 80/200
2/2 [==============================] - 0s 41ms/step - loss: 4.1828e-09 - categorical_accuracy: 1.0000
Epoch 81/200
2/2 [==============================] - 0s 31ms/step - loss: 4.1828e-09 - categor

Epoch 144/200
2/2 [==============================] - 0s 39ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 145/200
2/2 [==============================] - 0s 35ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 146/200
2/2 [==============================] - 0s 33ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 147/200
2/2 [==============================] - 0s 34ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 148/200
2/2 [==============================] - 0s 35ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 149/200
2/2 [==============================] - 0s 33ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 150/200
2/2 [==============================] - 0s 44ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 151/200
2/2 [==============================] - 0s 34ms/step - loss: 2.0914e-09 - categorical_accuracy: 1.0000
Epoch 152/200
2/2 [==============================] - 0s 34ms/step - loss

In [29]:
res = model.predict(x_test)
print(res)
print(actions[np.argmax(res[0])])
for i in range(len(res)):
    print(actions[np.argmax(res[i])])

[[1.0000000e+00 5.6286070e-10]
 [1.0000000e+00 3.2615669e-25]
 [4.8015521e-30 1.0000000e+00]]
on
on
on
off


In [30]:
# save weights
model.save('action.h5')

In [31]:
#evaluation using confusion matrix
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

yhat = model.predict(x_test)
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()
matrix = multilabel_confusion_matrix(ytrue, yhat)
print(matrix)
accuracy_score = accuracy_score(ytrue, yhat)
print(f"{accuracy_score= }")


[[[1 0]
  [0 2]]

 [[2 0]
  [0 1]]]
accuracy_score= 1.0
